### ISSUE TITLE
connecting to secure mqtt server

### ISSUE THREAD

**Issue by ali-shabani** [salmanzafar949/MQTT_Laravel#10]
Hi, How can I connect to secure mqtt server with this library. there is an option in config file that wants cert file to connect to **secure mqtt server**.
I don't know what is this rlly!
I secured my mqtt server with letsencrypt. there are 3 files named _**cert.pem, chain.pem, fullchain.pem**_ and I tried all of them and there was an error that says provided certificate file is not valid.
even I tried to download certificate file thorough openssl command (that I found in google) but that one also didn't work.
if I change prtocol in code from tcp to tls without providing stream_context_create I get this error:
`Connection failed! (Error: 0x20 0x05) `

can you help me to connect to mqtts protocol? did you know how can I **get ca file**?

**Comment by ali-shabani** [comment]
also I use MqttBox application on windows to test my server.
te settings for application to connect is:
```
Protocol: mqtts / tls
SSL / TLS Version: Auto
SSL / TLS Certificate Type: CA signed server certificate
```

**Comment by salmanzafar949** [comment]
hi, please make sure your certificate is valid.
I've been using ca.cert for one of our server and its working fine I've tested again it's working fine.
kindly make sure the client and server uses the same verification method.
here are the few links you can check:

http://www.steves-internet-guide.com/creating-and-using-client-certificates-with-mqtt-and-mosquitto/

http://www.steves-internet-guide.com/mosquitto-tls/
