### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by BalrajArpit** [salmanzafar949/MQTT_Laravel#11]
Eveything is configured perfectly but it failed to publish message.

bool(false) Failed

**Comment by salmanzafar949** [comment]
Whats the issue whats the error? have you set debug to true to check errors?
and also any example code?
it's way too vague  question.

**Comment by BalrajArpit** [comment]
Yes, it's set to debug to true. 

Debug True: bool(false) Failed
Debug False: Failed

**Comment by salmanzafar949** [comment]
Please provide any working example .
i'm unable to re-produce it
