### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by nicolas267** [salmanzafar949/MQTT_Laravel#12]
Hi, when I connect to the host and the configured port, I received the message: Connection failed! (Error: 0x48 0x50). my mqtt server is made with ** mosquitto ** without ssl

**Comment by salmanzafar949** [comment]
Have you tested you mqtt via terminal ?it seems your mqtt is not properly configured

**Comment by nicolas267** [comment]
and subscription in localhost and it works fine, I also tried to connect it with https://www.eclipse.org/paho/clients/js/utility/ and it also works

**Comment by salmanzafar949** [comment]
Please check you server configuration.you may have missed something.
i tested with live and local server of mqtt and its working fine

**Comment by deepshikha11grawlix** [comment]
Connection failed! (Error: 0x48 0x50) 
same issue 
when MQTT is working fine with 
![image](https://user-images.githubusercontent.com/102038823/181700354-8ddfabf6-d344-4c3f-bd55-d7a5260bf890.png)
