### ISSUE TITLE
Message published but ESP8266 not listening.

### ISSUE THREAD

**Issue by BalrajArpit** [salmanzafar949/MQTT_Laravel#13]
Message published which I can see on MQTT.fx but ESP8266 not listening.

**Comment by BalrajArpit** [comment]
Solved by changing client ID of web application.

**Comment by BalrajArpit** [comment]
Solved by changing client ID of web application.

**Comment by KulwinderKohli** [comment]
Hi, @BalrajArpit can you please tell me how did you fix it?
