### ISSUE TITLE
MQTT Message repetition on subscribe

### ISSUE THREAD

**Issue by w1lldone** [salmanzafar949/MQTT_Laravel#17]
Currently i'm developing a subscriber for storing MQTT data that published by IoT nodes. I use artisan command to subscribe to the MQTT broker. The problem is i keep getting double data from those devices eventhough they just published the data once. So i turned on debugging mode and i got this messages from my console:
```
"Storing data from LSL_c29d770f_1 at 2020-04-29 06:22:58"
eof receive going to reconnect for good measure
Connected to Broker
"Storing data from LSL_c29d770f_1 at 2020-04-29 06:23:12"
```
 `LSL_c29d770f_1` is the device id. The IoT devices only publishes the data every one minute. But because the subcriber tries to reconnect for good measure, that data was stored twice.
Does anyone know what is happening?

**Comment by LucBerge** [comment]
Does the IoT node publish with the retained flag set to true ?

**Comment by w1lldone** [comment]
Yes i think the retained value was set to true. Every time i start the subscriber, the data is retained from broker. But the one thing i want to know is, what does trigger `eof receive going to reconnect for good measure`?

**Comment by LucBerge** [comment]
Regarding [this issue](https://github.com/bluerhinos/phpMQTT/issues/42), it's a ping story. I can't really help you on it.

But if the subscriber restarts after receiving the message, it is normal to receive the data twice since you have the retained flag set to true.

**Comment by salmanzafar949** [comment]
The only way to stop this is to delete the topics and re create them or set it to null before publishing .
There is no other way
