### ISSUE TITLE
Qos

### ISSUE THREAD

**Issue by Soulreavertom** [salmanzafar949/MQTT_Laravel#2]
You shoud permit send the QoS, Retain Flag, Packet Identifier, DUP flag etc etc

**Comment by JustinBusschau** [comment]
Allow me to commit to this and I'll submit a PR for QoS and Retain

**Comment by salmanzafar949** [comment]
Sorry for the late reply.
Thank you so much for the comments. I've implemented it my self and it's already released in a new version v1.0.3.
Happy Coding.
