### ISSUE TITLE
php artisan vendor:publish --provider="Salman\Mqtt\MqttServiceProvider"  Unable to locate publishable resources

### ISSUE THREAD

**Issue by AdrianaTheo** [salmanzafar949/MQTT_Laravel#26]
Hello there,

When, I am arriving on the step to publish the class provider using:
`php artisan vendor:publish --provider="Salman\Mqtt\MqttServiceProvider" `

i am getting this error:
```
Unable to locate publishable resources.
Publishing complete.
```
I am using lumen 8.0. 

Thank you in advance

**Comment by salmanzafar40** [comment]
This seems to lumen issue run below commands : 

> 1 - php artisan clear-compiled
> 2 - composer dumpautoload

and after that run `php artisan vendor:publish --provider="Salman\Mqtt\MqttServiceProvider"`

reference: [this](https://stackoverflow.com/questions/60719259/unable-to-locate-publishable-resources)
