### ISSUE TITLE
PHP Version 7.4.3  Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by Maks-vint** [salmanzafar949/MQTT_Laravel#27]
at vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php:170
    166▕         $buffer .= chr($id >> 8);  $i++;
    167▕         $buffer .= chr($id % 256);  $i++;
    168▕         foreach($topics as $key => $topic){
    169▕             $buffer .= $this->strwritestring($key,$i);
  ➜ 170▕             $buffer .= chr($topic["qos"]);  $i++;
    171▕             $this->topics[$key] = $topic;
    172▕         }
    173▕         $cmd = 0x80;
    174▕         //$qos

**Comment by Maks-vint** [comment]
at vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php:170
    166▕         $buffer .= chr($id >> 8);  $i++;
    167▕         $buffer .= chr($id % 256);  $i++;
    168▕         foreach($topics as $key => $topic){
    169▕             $buffer .= $this->strwritestring($key,$i);
  ➜ 170▕             $buffer .= chr($topic["qos"]);  $i++;
    171▕             $this->topics[$key] = $topic;
    172▕         }
    173▕         $cmd = 0x80;
    174▕         //$qos

**Comment by ihsan138** [comment]
You're referring to 'Cannot use object of type Closure as array' error right?

**Comment by Petruccini** [comment]
I have the same issue, 'Cannot use object of type Closure as array' this is right

**Comment by Petruccini** [comment]
function subscribe($topics, $qos = 0){

        $i = 0;

        $buffer = "";

        $id = $this->msgid;

        $buffer .= chr($id >> 8);  $i++;

        $buffer .= chr($id % 256);  $i++;

        foreach($topics as $key => $topic){

            $buffer .= $this->strwritestring($key,$i);

            $buffer .= chr($topic["qos"]);  $i++;

            $this->topics[$key] = $topic;

        }

        $cmd = 0x80;

        //$qos

        $cmd +=	($qos << 1);

        $head = chr($cmd);

        $head .= chr($i);

 

        fwrite($this->socket, $head, 2);

        fwrite($this->socket, $buffer, $i);

        $string = $this->read(2);

 

        $bytes = ord(substr($string,1,1));

        $string = $this->read($bytes);

    }

**Comment by adnandogar** [comment]
is this resolved?

**Comment by adnandogar** [comment]
i checked, with 2.0 versions this error occurs, 
currently i downgraded this package to old version and that works fine:
 "salmanzafar/laravel-mqtt": "^1.0"

**Comment by ssarljames** [comment]
I also have this error. 

I tried to downgrade with **v1.0.9** but unable to see and receive subscription messages. 

I'm using PHP 7.4

**Comment by TheTonio** [comment]
Hi,
the problem seems to be in the "vendor/salmanzafar/laravel-mqtt/src/MqttClass/Mqtt.php" file.
The line 
`$topicData =  is_array($topic) ? $topic : $topics[$topic] = ["qos" => 0, "function" => $proc];`
seems to produce the wrong array.
This 
`is_array($topic) ? $topicData = collect($topic)->flatMap(function ($topic) use ($proc){ return [$topic => ["qos" => 0, "function" => $proc]]; })->all() : $topicData[$topic] = ["qos" => 0, "function" => $proc];`
seems to work fine.

I hope this helps.

**Comment by KurtBickenbach** [comment]
I'm getting this same error on subscribe.  The fix from TheTonio doesn't work for me in Larvel 8 with PHP version 8.0.0.

**Comment by salmanzafar949** [comment]
fixed in v2.0.7
