### ISSUE TITLE
Possible timeout issue

### ISSUE THREAD

**Issue by danijelk** [salmanzafar949/MQTT_Laravel#29]
We have a job which seems to end after the timeout of horizon (laravel), it seems like it does connect to mqtt server (default timeout 10s) but then seems to get stuck in the read() method, would it be a good idea to add an internal timeout here of some sort?
```

Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(195): Illuminate\Queue\Worker->maxAttemptsExceededException()
#1 /app/vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php(149): Illuminate\Queue\Worker->Illuminate\Queue\{closure}()
#2 /app/vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php(126): Salman\Mqtt\MqttClass\MqttService->read()
#3 /app/vendor/salmanzafar/laravel-mqtt/src/MqttClass/Mqtt.php(79): Salman\Mqtt\MqttClass\MqttService->connect()
#4 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Salman\Mqtt\MqttClass\Mqtt->ConnectAndPublish()
```

**Comment by salmanzafar949** [comment]
we already have a timeout that can set from config file..
do you want to pass timeout as param to the methods?

**Comment by danijelk** [comment]
> we already have a timeout that can set from config file..
> do you want to pass timeout as param to the methods?

Was some time ago we had a look at this, what I recall is that the fread tries indefinatly which leads to a job-timeout instead of a mqtt timeout

```
        while (!feof($this->socket) && $togo>0) {
            $fread = fread($this->socket, $togo);
            $string .= $fread;
            $togo = $int - strlen($string);
        }
```

So here I would suggest having an internal timeout checker that is able to break out if it times out, but I can't replicate the issue and we havn't seen it in our bugtracker for a while so probably not worth the change at this time :) Thanks for the response though.
