### ISSUE TITLE
ErrorException: Required parameter $debug follows optional parameter in PHP 8.0

### ISSUE THREAD

**Issue by TMogdans** [salmanzafar949/MQTT_Laravel#31]
`ErrorException: Required parameter $debug follows optional parameter $cafile in file /var/www/html/solarsystem-service/vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php on line 36`

The parameter `$debug` of `MqttService::__construct` is not an optional parameter, but follows an optional parameter. 

Possible solution is to move it before optional parameters.

PR: https://github.com/salmanzafar949/MQTT-Laravel/pull/32

**Comment by salmanzafar949** [comment]
Will set $debug=false by default so we don't have to change the entire order.

**Comment by salmanzafar949** [comment]
fixed in v2.0.5
