### ISSUE TITLE
可以同时监听多个tcp地址吗？

### ISSUE THREAD

**Issue by shunhua** [salmanzafar949/MQTT_Laravel#34]

**Comment by shunhua** [comment]
我已经fork下来 ，修改发布过了，有需要的请前去下载安装
https://github.com/shunhua/mqtt

**Comment by salmanzafar949** [comment]
currently no

**Comment by shunhua** [comment]
> 

目前我是修改了 初始化配置
![image](https://user-images.githubusercontent.com/11988030/106421616-f9e05500-6497-11eb-8f7d-980ace381572.png)
