### ISSUE TITLE
Error Cannot use object of type Closure as array in Mqtt::ConnectAndSubscribe

### ISSUE THREAD

**Issue by gsudhanshu** [salmanzafar949/MQTT_Laravel#38]
I am trying to build a notification service in my laravel+angular application using mqtt

while testing mqtt on laravel I got the error "Cannot use object of type Closure as array"

Here is my code: (error is coming on line where I call Mqtt::ConnectAndSubscribe

Mqtt::ConnectAndSubscribe("User".$toUId, function($topic, $msg){
            \Log::Debug("Msg Received, topic: ".$topic." , message: ".$msg);
        }, "User".$uId);

`Cannot use object of type Closure as array {"exception":"[object] (Error(code: 0): Cannot use object of type Closure as array at /home/sudhanshug/ws/hytech/EVA-video-call/backend/vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php:172)
[stacktrace]
#0 /home/sudhanshug/ws/hytech/EVA-video-call/backend/vendor/salmanzafar/laravel-mqtt/src/MqttClass/Mqtt.php(107): Salman\\Mqtt\\MqttClass\\MqttService->subscribe()
#1 /home/sudhanshug/ws/hytech/EVA-video-call/backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Salman\\Mqtt\\MqttClass\\Mqtt->ConnectAndSubscribe()
#2 /home/sudhanshug/ws/hytech/EVA-video-call/backend/app/Http/Controllers/APIController.php(146)`

**Comment by Casdak7** [comment]
This is a problem I encoutered as well in Laravel 8 and php 7.3.27.
I workaround is substituting the contents of the if statement in the foreach($topics as $key => $topic) in the subscribe function in the file vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php for this:
```
$buffer .= $this->strwritestring($key,$i);
$callback = func_get_args()[0];
$buffer .= chr($callback["qos"]);
$i++;
$this->topics[$key] = $topic;
```

More about the problem can be found here: https://stackoverflow.com/questions/40332428/convert-closure-object-to-array

The full subscribe function:
```
/* subscribe: subscribes to topics */
    function subscribe($topics, $qos = 0){
        $i = 0;
        $buffer = "";
        $id = $this->msgid;
        $buffer .= chr($id >> 8);  $i++;
        $buffer .= chr($id % 256);  $i++;
        foreach($topics as $key => $topic){
            if (!empty($topic))
            {
                $buffer .= $this->strwritestring($key,$i);
                $callback = func_get_args()[0];
                $buffer .= chr($callback["qos"]);
                $i++;
                $this->topics[$key] = $topic;
            }
        }
        $cmd = 0x80;
        //$qos
        $cmd +=	($qos << 1);
        $head = chr($cmd);
        $head .= chr($i);

        fwrite($this->socket, $head, 2);
        fwrite($this->socket, $buffer, $i);
        $string = $this->read(2);

        $bytes = ord(substr($string,1,1));
        $string = $this->read($bytes);
    }
```
