### ISSUE TITLE
subsecripe support.

### ISSUE THREAD

**Issue by uwejan** [salmanzafar949/MQTT_Laravel#4]
Hello, i have not tested the package yet, but i noticed on the description that subsecriping is not supported yet, my project will require publishing and subsecriping too, thus l, kindly asking is there a timeline for supporting subsecriping to topics? 
Regards.

**Comment by salmanzafar949** [comment]
Hi, i'm busy on on some other project but yes surely the subscription part will be available soon may be in 2 weeks or may be in a month so i can't give you deadline  for this.

**Comment by uwejan** [comment]
Can we at least keep it open to track the status of it?

**Comment by salmanzafar949** [comment]
okay sure
