### ISSUE TITLE
Error: unable to subscribe

### ISSUE THREAD

**Issue by wilianx7** [salmanzafar949/MQTT_Laravel#42]
PHP Version: 7.4.18
Laravel version: 8.40.0

Subscribing to topics is not possible using the methods below:

## Example 1

Code:
![image](https://user-images.githubusercontent.com/42422976/117087183-199c4900-ad25-11eb-9d1a-9f66a2c5d878.png)

Result:
![image](https://user-images.githubusercontent.com/42422976/117087235-33d62700-ad25-11eb-9166-2aeaf2ffa15a.png)

## Example 2

Code:
![image](https://user-images.githubusercontent.com/42422976/117087315-74ce3b80-ad25-11eb-8d62-f83187950f14.png)

Result:
![image](https://user-images.githubusercontent.com/42422976/117087330-81529400-ad25-11eb-9612-196fed7907f2.png)

## Solution

Replacing the construction of the "topicData" variable with this code, the result occurs as expected:

Code:
![image](https://user-images.githubusercontent.com/42422976/117087750-c9be8180-ad26-11eb-9bc6-af3f5b6f935e.png)

Result:
![image](https://user-images.githubusercontent.com/42422976/117087715-aeec0d00-ad26-11eb-9fea-90d881b2c896.png)

**Comment by salmanzafar949** [comment]
Good catch & fix
