### ISSUE TITLE
stream_socket_client(): unable to connect to tcp://mqtt.test.com:1883 (Connection timed out) #130

### ISSUE THREAD

**Issue by nidhinnp** [salmanzafar949/MQTT_Laravel#47]
at vendor/salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php:79
     75▕             }
     76▕             $socketContext = stream_context_create($sslOptions);
     77▕             $this->socket = stream_socket_client("tls://" . $this->address . ":" . $this->port, $errno, $errstr, $this->timeout, STREAM_CLIENT_CONNECT, $socketContext);
     78▕         } else {
  ➜  79▕             $this->socket = stream_socket_client("tcp://" . $this->address . ":" . $this->port, $errno, $errstr, $this->timeout, STREAM_CLIENT_CONNECT);
     80▕         }
     81▕         if (!$this->socket ) {
     82▕             if($this->debug) error_log("stream_socket_create() $errno, $errstr \n");
     83▕             return false;

      +1 vendor frames 
  2   app/Mqtt/Mqtt.php:101
      Salman\Mqtt\MqttClass\MqttService::connect()

  3   routes/console.php:77
      App\Mqtt\Mqtt::ConnectAndSubscribe()
`

**Comment by salmanzafar949** [comment]
Looks like your mqtt server is not running make sure it is working

**Comment by nidhinnp** [comment]
Thanks for your kind information
