### ISSUE TITLE
prevent to generate random id

### ISSUE THREAD

**Issue by smnikzad91** [salmanzafar949/MQTT_Laravel#7]
hi
i am using your library for mqtt
is there any way to set fixed id ?
any time publish message , id change

**Comment by salmanzafar40** [comment]
To set fix id you need to made changes in 
`src/MqttClass/Mqtt.php
`
and have to make changes in `ConnectAndPublish` method on below line:

`        $client = new MqttService($this->host,$this->port, rand(0,100), $this->cert_file, $this->debug);
`
in the above line change `rand(0,100)` to your desired client id.


Thanks.

**Comment by salmanzafar949** [comment]
To set fix id you need to made changes in
`src/MqttClass/Mqtt.php `

and have to make changes in `ConnectAndPublish` method on below line:

`$client = new MqttService($this->host,$this->port, rand(0,100), $this->cert_file, $this->debug);`

in the above line change `rand(0,100)` to your desired client id.

Thanks.

**Comment by smnikzad91** [comment]
thanks for your fast reply
i want to set client  id according to auth user id , how i can do that ?
best guard

**Comment by salmanzafar949** [comment]
Make the `ConnectAndPublish` function accepts user_id as third parameter 

```
 public function ConnectAndPublish($topic, $msg, $id)
    {
        $client = new MqttService($this->host,$this->port, $id, $this->cert_file, $this->debug);
        if ($client->connect(true, null, $this->username, $this->password))
        {
            $client->publish($topic,$msg);
            $client->close();
            return true;
        }
        return false;
    }
```

and when you call this in your controller you can do something like below

`Mqtt::ConnectAndPublish('a','hello', Auth::user()->id)
`
Thanks.

**Comment by smnikzad91** [comment]
Thanks a lot
