### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by roXii033** [salmanzafar949/MQTT_Laravel#8]
Since php version 7.4 accessing string offsets and array elements with curly brace syntax is deprecated. https://wiki.php.net/rfc/deprecate_curly_braces_array_access

> ErrorException  : Array and string offset access syntax with curly braces is deprecated
at /.../salmanzafar/laravel-mqtt/src/MqttClass/MqttService.php:110

**Comment by salmanzafar949** [comment]
add support for php 7.4 done
