### ISSUE TITLE
Subscribe to topic not working

### ISSUE THREAD

**Issue by geomi88** [salmanzafar949/MQTT_Laravel#9]
When i publish a topic and subscribed to that topic i am unable to receive any published messages,the page keeps on loading without any response.My intent is to save the received message to db.

**Comment by jsinghvirdi** [comment]
publishing the topic is working but after subscription message not receiving, same issue as geomi88

**Comment by geomi88** [comment]
> publishing the topic is working but after subscription message not receiving, same issue as geomi88

**Comment by geomi88** [comment]
> publishing the topic is working but after subscription message not receiving, same issue as geomi88

Its working now.Open terminal and use wget

**Comment by KulwinderKohli** [comment]
![image](https://user-images.githubusercontent.com/11345066/77621160-eacc7480-6f61-11ea-8422-f0bc8baab1bb.png)

**Comment by KulwinderKohli** [comment]
I am not getting any message.

**Comment by ssarljames** [comment]
Me too, I'm not getting any messages on subscription.
